version: "3"

services:
  mysql:
    image: wonderlandpark/mariadb-mroonga:latest
    hostname: mysql
    container_name: mysql
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/ubuntu/mysql-beta:/var/lib/mysql
  web:
    container_name: web
    ports:
      - 4000:3000
    links:
      - mysql
    image: wonderlandpark/koreanbots:latest